---
#
# Ansible managed
#
repository:
  description: Install the Elastic repository on your system.
  homepage: https://robertdebock.nl/
  topics: elasticrepo, monitoring, ansible, molecule, tox, playbook
