---
# handlers file for elastic_repo

- name: Switch back to default crypto policy
  ansible.builtin.command:
    cmd: update-crypto-policies --set DEFAULT
  when:
    - elastic_repo_revert_crypto_policy

- name: Uninstall crypto-policies-scripts
  ansible.builtin.package:
    name: crypto-policies-scripts
    state: absent
  when:
    - elastic_repo_cleanup_requirements
