---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Install elastic product
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - metricbeat
